### ISSUE TITLE
It doesn't remove the line ending like a regular cut, just blanks the line.

### ISSUE THREAD

**Issue by fadec** [vscode-plugins/Copy-Gather-Paste#1]
It doesn't remove the line ending like a regular cut, just blanks the line. This makes it necessary to move the cursor to cut multiple adjacent lines.

**Comment by serge1** [comment]
I could not reproduce the issue according to the description. Would you please explain it more? Please describe exact scenario and cursor positions. Thank you

**Comment by serge1** [comment]
I could not reproduce the issue according to the description. Would you please explain it more? Please describe exact scenario and cursor positions. Thank you

**Comment by serge1** [comment]
Due to the lack of the feedback, I am closing the issue. Please reopen if the problem persists.
